<?php

namespace Fishyboat21\SimpleApi\Command;

use Fishyboat21\SimpleApi\Router\RouteScanner;
use RuntimeException;

/**
 * CLI command to generate the route cache file.
 *
 * Usage: vendor/bin/simple-api route:generate [options]
 *
 * Scans the Api directory for ApiHandler classes, reads their #[Route]
 * attributes, derives URL paths from the filesystem convention, and
 * writes a trie-based route cache to a PHP file.
 */
class RouteGenerateCommand
{
    /**
     * Execute the command.
     *
     * @param array<string, string> $options Keyed options from CLI args.
     * @return int Exit code (0 = success, 1 = failure).
     */
    public function execute(array $options = []): int
    {
        $scanDir = $options['scan'] ?? 'src/Api';
        $baseNamespace = $options['namespace'] ?? 'App\\Api';
        $outputFile = $options['output'] ?? 'storage/routes.php';
        $baseUrlPath = $options['base-url'] ?? 'api';

        // Resolve relative paths against working directory
        $cwd = getcwd();
        if (!str_starts_with($scanDir, '/') && !preg_match('/^[A-Z]:/', $scanDir)) {
            $scanDir = $cwd . DIRECTORY_SEPARATOR . $scanDir;
        }
        if (!str_starts_with($outputFile, '/') && !preg_match('/^[A-Z]:/', $outputFile)) {
            $outputFile = $cwd . DIRECTORY_SEPARATOR . $outputFile;
        }

        if (!is_dir($scanDir)) {
            fprintf(STDERR, "Error: Scan directory not found: %s\n", $scanDir);
            fprintf(STDERR, "Create 'src/Api/' and add your endpoint classes first.\n");
            return 1;
        }

        $scanner = new RouteScanner(
            scanDir: $scanDir,
            baseNamespace: $baseNamespace,
        );

        try {
            $trie = $scanner->scan();
        } catch (RuntimeException $e) {
            fprintf(STDERR, "Error: %s\n", $e->getMessage());
            return 1;
        }

        // Write the cache file
        $content = $this->generateCacheFile($trie);
        $dir = dirname($outputFile);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        if (file_put_contents($outputFile, $content) === false) {
            fprintf(STDERR, "Error: Failed to write route cache to %s\n", $outputFile);
            return 1;
        }

        $routeCount = $this->countRoutes($trie);
        printf("Route cache generated: %d route(s) written to %s\n", $routeCount, $outputFile);
        return 0;
    }

    /** Generate the PHP cache file content. */
    private function generateCacheFile(array $trie): string
    {
        $export = var_export($trie, true);
        // Make it readable with array short syntax (var_export uses array(), convert to [])
        // This is cosmetic — var_export output is fine for opcache

        return <<<PHP
<?php

/**
 * Route cache — auto-generated by simple-api route:generate.
 * DO NOT EDIT BY HAND.
 *
 * Generated at: {$this->now()}
 */

return {$export};

PHP;
    }

    private function now(): string
    {
        return date('Y-m-d H:i:s');
    }

    /** Count total routes in the trie (sum of all __handlers entries). */
    private function countRoutes(array $trie): int
    {
        $count = 0;
        foreach ($trie as $key => $value) {
            if ($key === '__handlers') {
                $count += count($value);
            } elseif ($key === '__name') {
                continue;
            } elseif (is_array($value)) {
                $count += $this->countRoutes($value);
            }
        }
        return $count;
    }
}
